name: gh

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  gh:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@master

      - uses: pnpm/action-setup@v2.0.1
        with:
          version: 7.11.0

      - name: Setup node env
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Generate
        run: pnpm build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
